RestorationStore/RestorationStore/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestorationStore.Domain.Model;
using RestorationStore.Domain;
namespace RestorationStore.Controllers {
    [Authorize]
    public class RequestController : Controller
    {
        Repository<Request> requestContext = new Repository<Request>();
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Index(){
            return View("CreateRequest");
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult CreateRequest(Request request,
                                          HttpPostedFileBase image) {
            if(ModelState.IsValid) {
                if(image != null) {
                    request.ImageMimeType = image.ContentType;
                    request.InitialImage = new byte[image.ContentLength];
                    image.InputStream.Read(request.InitialImage, 0, image.ContentLength);
                }
                request.Estatus = "Pending";
                request.InitialDate = System.DateTime.Now;
                if(request.Contact.Phone!=null){
                    request.Contact.Phone = request.Contact.Phone.Replace("-", "");
                }
               requestContext.Add(request);
               requestContext.Save();
                return RedirectToAction("Index","Home");
            }
            return View(request);
        }
       
        [HttpGet]
        public ActionResult StartRequest(int id_request) {
            System.Linq.Expressions.Expression<Func<Request, bool>>
               expr = x => x.Id == id_request;
            Request request = requestContext.FindOne(expr);
            if(request==null){
                return RedirectToAction("Index","Home");
            }
            return View(request);
        }
        
        [HttpPost]
        public string SetInProgress(int  id_request) {
            System.Linq.Expressions.Expression<Func<Request, bool>>
               expr = x => x.Id == id_request;
            Request request = requestContext.FindOne(expr);
            if(request != null) {
                request.Estatus = "In progress";
                requestContext.Edit(request);
                requestContext.Save();
                return "<h2>Thanks!!!Request initialized correctly</h2>";
            }
            return "<h2>Sorry!!!The request does not exist!!!</h2>";
        }
        
        [HttpGet]
        public ActionResult SetInStop(int id_request) {
            System.Linq.Expressions.Expression<Func<Request, bool>>
               expr = x => x.Id == id_request;
            Request request = requestContext.FindOne(expr);
            if(request == null) {
                return RedirectToAction("Index", "Home");
            }
            return View(request);
        }
       
        [HttpPost]
        public string SetInStopRequest(int id_request) {
            System.Linq.Expressions.Expression<Func<Request, bool>>
               expr = x => x.Id == id_request;
            Request request = requestContext.FindOne(expr);
            if(request != null) {
                request.Estatus = "Pending";
                requestContext.Edit(request);
                requestContext.Save();
                return "<h2>The request has been stopped</h2>";
            }
            return "<h2>Sorry!!!The request does not exist!!!</h2>";
        }

        [AllowAnonymous]
        public FileContentResult GetImage(int id_request) {
            Request request = requestContext.FindOneForId(id_request);
            if(request != null) {
                return File(request.InitialImage, request.ImageMimeType);
            } else {
                return null;
            }
        }
    }
}

RestorationStore/RestorationStore/Controllers/ResponseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestorationStore.Domain;
using RestorationStore.Domain.Model;
namespace RestorationStore.Controllers
{
    public class ResponseController : Controller
    {
        Repository<Respons> responseContext = new Repository<Respons>();
        Repository<Request> requestContext = new Repository<Request>();
        [Authorize]
        [HttpGet]
        public ActionResult CreateResponse(int id_request) {
            Respons response = new Respons();
            Request request = requestContext.FindOneForId(id_request);
            if(request==null){
                return RedirectToAction("Index","Home");
            }
            response.Request = request;
            response.Cost = 1;
            response.Id_Request = request.Id;
            return View("CreateResponse",response);
        }
        [Authorize]
        [HttpPost]
        public ActionResult CreateResponse(Respons response, 
                                           HttpPostedFileBase image) {
            Request request = requestContext.FindOneForId(response.Id_Request);
            if(ModelState.IsValid) {
                if(image != null) {
                    response.ImageMimeType = image.ContentType;
                    response.FinalImage = new byte[image.ContentLength];
                    image.InputStream.Read(response.FinalImage, 0, image.ContentLength);
                   
                    response.FinalDate = System.DateTime.Now;
                    request.Estatus = "Completed";
                    responseContext.Add(response);
                    requestContext.Edit(request);
                    responseContext.Save();
                    requestContext.Save();
                    return RedirectToAction("Index", "Home");
                } else {
                    ModelState.AddModelError("","Please, load the final image.");
                }
            }
            response.Request = request;
            return View(response);
        }
        [HttpGet]
        public ActionResult GetAllResponses() {
            return View(responseContext.FindAll().OrderBy(p => p.FinalDate));
        }

        public FileContentResult GetImage(int id) {
            Respons response = responseContext.FindOneForId(id);
            if(response != null) {
                return File(response.FinalImage, response.ImageMimeType);
            } else {
                return null;
            }
        }

        [HttpGet]
        public ActionResult DetailResponse(int id) {
            Respons response = responseContext.FindOneForId(id);
            if(response==null){
                return RedirectToAction("Index","Home");
            }
            return View(response);
        }
    }
}

RestorationStore/RestorationStore/Views/Response/CreateResponse.cshtml
@model RestorationStore.Domain.Model.Respons

@{
    ViewBag.Title = "Create Response";
}
@section scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/Validation/ImageSize.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}
<h2>Create Response</h2>
    <div >
        <div id="pan_izquierdo">
@using(Html.BeginForm("CreateResponse", "Response",
    FormMethod.Post,
    new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        @Html.Hidden("id_request", Model.Id_Request)
            <legend>Respons</legend>
            <div class="editor-label">
                @Html.LabelFor(model => model.Cost)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Cost)
                @Html.ValidationMessageFor(model => model.Cost)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
            <div class="editor-field">
                <div>Load final image: <input id="upload-file" type="file" name="Image" accept="image/png,image/jpeg" /></div>
            </div>
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
}
    <div>
        @* @Html.ActionLink("Back to List", "Index")*@
    </div>
        </div>

        <div id="pan_centro">
            <fieldset>
                <legend>Request</legend>
                <div>
                    @Html.Partial("~/Views/Request/DetailRequestFullPartial.cshtml", Model.Request)
                </div>
            </fieldset>
</div>
    </div>

RestorationStore/RestorationStore/Views/Response/DetailResponse.cshtml
@model RestorationStore.Domain.Model.Respons

@{
    ViewBag.Title = "Detail completed request";
}
@section scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/Response/DetailResponse.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}
<h2>Detail completed request</h2>
<div>
    <div id="pan_izquierdo">

            <fieldset>
                <legend>Respons</legend>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Request.Title.TitleMessage)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Request.Title.TitleMessage)
                </div>
                <div>
                    @if(@Model.Id != null) {
                        <div class="editor-label">Final Image</div>
                        <div class="editor-field">
                            <img width="100" height="100"
                                 src="@Url.Action("GetImage",
                                    "Response",
                        new { id=@Model.Id })" />
                        </div>
                    }
                </div>
                <div>
                    @if(@Model.Id != null) {
                        <div class="editor-label">Initial Image</div>
                        <div class="editor-field">
                            <img width="100" height="100"
                                 src="@Url.Action("GetImage",
                                    "Request",
                        new { id_request=@Model.Id_Request })" />
                        </div>
                    }
                </div>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Cost)
                </div>
                <div class="display-field">
                   $ @Html.DisplayFor(model => model.Cost)
                </div>
                <div class="display-label">
                   Final description
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </div>
                <div class="display-label">
                    Initial description
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Request.Description)
                </div>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.FinalDate)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.FinalDate)
                </div>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Request.InitialDate)
                </div>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Request.InitialDate)
                </div>
            </fieldset>
    </div>

    <div id="pan_centro">
        <fieldset>
            <legend>Commentaries</legend>
            <form id="messageForm">
                @Html.Hidden("id_response", Model.Id)
                <div class="display-label">
                    Author
                </div>
                <div class="display-field">
                    <input id="Author" name="Author" />
                </div>
                <div class="display-label">
                    Commentary
                </div>
                <div class="display-field">
                    <input id="Message" name="Message" 
                           class="text-box single-line" 
                            data-val="true" 
                            data-val-length="Please, no more than 100 characters" 
                            data-val-length-max="100" 
                            data-val-length-min="1" 
                           data-val-required="Please, introduce a commentary" value="" />
                    <span class="field-validation-valid" data-valmsg-for="Message" data-valmsg-replace="true"></span>
                </div>
                
            </form>
            <button id="addMessage" type="submit">Add message</button>
            <div>
                <table>
                    <thead>
                        <tr>
                            <th>Author</th>
                            <th>Commentary</th>
                        </tr>
                    </thead>
                    <tbody id="tableCommentary">
                        <tr><td colspan="2">The data is loading</td></tr>
                    </tbody>
                </table>
            </div>
        </fieldset>
    </div>
</div>

RestorationStore/RestorationStore/Views/Response/GetAllResponses.cshtml
@model IEnumerable<RestorationStore.Domain.Model.Respons>

@{
    ViewBag.Title = "Completed Requests";
}
@section scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript" src="~/Scripts/Utils/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/Utils/Table.js" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jqueryval")
}
<h2>Completed Requests</h2>

<table id="myTable" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Request.Title.TitleMessage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FinalDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model) {
            <tr>
                <td>
                    @if(item.Id != null) {
                        <div style="float:left;margin-right:20px">
                            <img width="75" height="75"
                                 src="@Url.Action("GetImage",
                                    "Response",
                        new { id=item.Id })" />
                        </div>
                    }
                </td>
                <td>
                    @Html.ActionLink(item.Request.Title.TitleMessage,
               "DetailResponse", "Response", new { id = item.Id }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FinalDate)
                </td>
            </tr>
        }
    </tbody>
</table>